src/global/utils/RandomUtil.java
=> Optimize bin assignment

src/global/BaseTest.java, src/global/variables/Clause.java, src/global/variables/NewLine.java, src/global/variables/RandomChar.java, src/global/variables/RandomDouble.java, src/global/variables/RandomInteger.java, src/global/variables/StringLiteral.java, src/global/variables/wrappers/AnyOf.java, src/global/variables/wrappers/Optional.java
Change Clause to an abstract class, and add name parameter. Added getItemByName with O(n) implementation. Might need to be improved later, but this works as intended for now.
Closes #7
=> Added Get Item by Name

src/global/BaseTest.java, src/global/variables/IntegerLiteral.java, src/temp/ClauseExample.java, src/temp/Example.java, src/temp/QuestionExample.java
+ rename expected output to testSentence()
+ added integer literal
+ fix getByName()
Closes #27
=> Integer Literal + Minor Fixes

src/global/BaseRandomTest.java, src/global/utils/RandomUtil.java, src/global/utils/RegexUtil.java, src/global/variables/Clause.java, src/global/variables/clauses/IntegerLiteral.java, src/global/variables/clauses/NewLine.java, src/global/variables/clauses/RandomChar.java, src/global/variables/clauses/RandomClause.java, src/global/variables/clauses/RandomDouble.java, src/global/variables/clauses/RandomInteger.java, src/global/variables/clauses/StringLiteral.java, src/temp/ClauseExample.java, src/temp/QuestionExample.java
+ moved clauses in their own package
+ moved some functions from RandomUtil to RegexUtil (they seemed better there)
+ because of ^ some static method references had to be updated
Closes #33
=> Minor moves + renames

src/global/BaseTest.java, src/global/tools/InvalidClauseException.java, src/global/utils/RegexUtil.java, src/global/variables/Clause.java, src/global/variables/clauses/IntegerLiteral.java, src/temp/ProphetRobot.java, src/temp/QuestionExample.java
=> Extend IntegerLiteral to include ranges

src/global/utils/RegexUtil.java
+ make ending with a carriage return optional
Closes #46
=> Fix print vs println bug

src/global/variables/clauses/DoubleLiteral.java, src/temp/QuestionExample.java
=> Add more specific message for double literal

src/global/BaseRandomTest.java, src/global/BaseTest.java, src/global/exceptions/InvalidClauseException.java, src/global/exceptions/InvalidTestOptionException.java, src/global/tools/TestOption.java, src/global/tools/TestSentenceUtil.java, src/global/utils/RegexUtil.java, src/global/variables/Clause.java, src/global/variables/RandomClause.java, src/global/variables/clauses/DoubleLiteral.java, src/global/variables/clauses/IntegerLiteral.java, src/global/variables/clauses/PlaceHolder.java, src/global/variables/clauses/RandomChar.java, src/global/variables/clauses/RandomDouble.java, src/global/variables/clauses/RandomInteger.java, src/temp/ClauseExample.java, src/temp/Example.java
+ added PlaceHolder clauses & clause injection
+ runWithInput helper method
Closes #30
Closes #15
=> Input based testing

src/global/utils/RegexUtil.java, src/global/variables/clauses/DoubleLiteral.java, src/temp/ProphetRobot.java, src/temp/QuestionExample.java
=> Add negative number support for all numeric clauses

.gitignore, src/global/utils/RegexUtil.java, src/global/variables/clauses/IntegerLiteral.java
+ allow IntegerLiteral to always match negative numbers
> We'll need to additionally merge this into `beta` to ensure the change persist there too
Closes #104
=> Fix negative integer issue

src/global/BaseRandomTest.java, src/global/BaseTest.java, src/global/exceptions/InvalidClauseException.java, src/global/exceptions/InvalidTestOptionException.java, src/global/tools/TestOption.java, src/global/tools/TestSentenceUtil.java, src/global/utils/RegexUtil.java, src/global/variables/Clause.java, src/global/variables/RandomClause.java, src/global/variables/clauses/DoubleLiteral.java, src/global/variables/clauses/IntegerLiteral.java, src/global/variables/clauses/PlaceHolder.java, src/global/variables/clauses/RandomChar.java, src/global/variables/clauses/RandomDouble.java, src/global/variables/clauses/RandomInteger.java, src/temp/ClauseExample.java, src/temp/Example.java
=> Input testing and Injections

src/global/BaseRandomTest.java, src/global/BaseTest.java, src/global/tools/Logger.java, src/global/utils/RandomUtil.java, src/global/utils/RegexUtil.java, src/global/variables/clauses/RandomDouble.java, src/global/variables/clauses/RandomInteger.java
=> Semantic restructure

src/global/BaseTest.java, src/global/tools/TestSentenceUtil.java
=> Multiple placedholder injections

src/pre_defined_classes/mathematical_program/medium/q1/BMI.java, src/pre_defined_classes/mathematical_program/medium/q1/BMITest.java, src/pre_defined_classes/mathematical_program/medium/q1/MainTest.java
I can't seem to get the clause test working even when I copy paste the code output and hardcode it
=> pre_defined_classes-mathematical_program-medium-q1

src/pre_defined_classes/mathematical_program/medium/q2/Heron.java, src/pre_defined_classes/mathematical_program/medium/q2/HeronTest.java, src/pre_defined_classes/mathematical_program/medium/q2/MainTest.java
=> pre defined classes-mathematical program-medium-q2

src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q1/MainTest.java, src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q1/PayrollTax.java, src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q1/ArithmeticStar.java, src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q1/MainTest.java
=> pre_defined_classes-simple_programs_taking_numeric_user_input-medium-q1

src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q2/MainTest.java, src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q2/SquareSpace.java
=> pre_defined_classes-simple_programs_taking_numeric_user_input-medium-q2

src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q3/MainTest.java, src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q3/SwappingGoodness.java
=> pre_defined_classes-simple_programs_taking_numeric_user_input-medium-q3

src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q4/Age.java, src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q4/MainTest.java
=> pre_defined_classes-simple_programs_taking_numeric_user_input-medium-q4

src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q5/MainTest.java, src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q5/MathSquareRoot.java
=> pre_defined_classes-simple_programs_taking_numeric_user_input-medium-q5

src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q3/MainTest.java, src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q3/OldFolks.java
=> pre_defined_classes-simple_programs_taking_numeric_user_input-hard-q3

src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q4/Discount.java, src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q4/MainTest.java
=> pre_defined_classes-simple_programs_taking_numeric_user_input-hard-q4

src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q5/LetterCalculator.java, src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q5/MainTest.java
=> pre_defined_classes-simple_programs_taking_numeric_user_input-hard-q5

src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q1/Greetings.java, src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q1/MainTest.java
=> pre_defined_classes-simple_programs_taking_string_user_input-medium-q1

src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q2/GuessCityName.java, src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q2/MainTest.java
=> pre_defined_classes-simple_programs_taking_string_user_input-medium-q2

src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q3/CourseNames.java, src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q3/MainTest.java
=> pre_defined_classes-simple_programs_taking_string_user_input-medium-q3

src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q4/CompareNames.java, src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q4/MainTest.java
=> pre_defined_classes-simple_programs_taking_string_user_input-medium-q4

src/pre_defined_classes/simple_porgrams_taking_string_user_input/medium/q5/MainTest.java, src/pre_defined_classes/simple_porgrams_taking_string_user_input/medium/q5/WordPluralizer.java
=> pre_defined_classes-simple_programs_taking_string_user_input-medium-q5

src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q1/MainTest.java, src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q1/UpperOrLower.java
=> pre_defined_classes-simple_programs_taking_string_user_input-hard-q1

src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q2/CheckEnding.java, src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q2/MainTest.java
=> pre_defined_classes-simple_programs_taking_string_user_input-hard-q2

src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q3/MainTest.java, src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q3/removeVowel.java
=> pre_defined_classes-simple_programs_taking_string_user_input-hard-q3

src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q4/CompareStrings.java, src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q4/MainTest.java
=> pre_defined_classes-simple_programs_taking_string_user_input-hard-q4

src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q5/MainTest.java, src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q5/orderHalf.java
=> pre_defined_classes-simple_programs_taking_string_user_input-hard-q5

src/conditionals/programs_with_decision_points/medium/q1/LetterBox.java, src/conditionals/programs_with_decision_points/medium/q1/MainTest.java
=> conditionals-programs_with_decision_points-medium-q1

src/conditionals/programs_with_decision_points/medium/q2/LetterGrade.java, src/conditionals/programs_with_decision_points/medium/q2/MainTest.java
=> conditionals-programs_with_decision_points-medium-q2

src/conditionals/programs_with_decision_points/medium/q3/MainTest.java, src/conditionals/programs_with_decision_points/medium/q3/Order.java
=> conditionals-programs_with_decision_points-medium-q3

src/conditionals/programs_with_decision_points/medium/q4/ForeGolf.java, src/conditionals/programs_with_decision_points/medium/q4/MainTest.java
=> conditionals-programs_with_decision_points-medium-q4

src/conditionals/simple_programs_with_decision_points/hard/q2/HistoricMoment.java, src/conditionals/simple_programs_with_decision_points/hard/q2/MainTest.java
=> conditionals-simple_programs_with_decision_points-hard-q2

.gitignore, src/test/BasicRandomCode.java, src/test/BasicRandomCodeTest.java, src/test/MultipleInjectionCode.java, src/test/MultipleInjectionCodeTest.java, src/test/RandomWithInputCode.java, src/test/RandomWithInputCodeTest.java, src/test/RunWithInputCustomErrorCode.java, src/test/RunWithInputCustomErrorCodeTest.java
+ add test files used to troubleshoot features in the framework
Hopefully, these can be used as a pseudo testing framework to ensure different parts of the framework are working as intended. Coverage is low and it contains a mix of tests designed to fail and tests designed to pass, so it's intended that the tests are played around to validate that the feature works fully.
=> Add framework troubleshoot files

src/conditionals/simple_programs_with_decision_points/hard/q7/MainTest.java, src/conditionals/simple_programs_with_decision_points/hard/q7/MaxItOut.java
=> conditionals-simple_programs_with_decision_points-hard-q7

src/conditionals/programs_with_decision_points/hard/q1/MainTest.java, src/conditionals/programs_with_decision_points/hard/q1/SleepyTimeAgain.java
=> conditionals-programs_with_decision_points-hard-q1

src/conditionals/programs_with_decision_points/hard/q2/Calculator.java, src/conditionals/programs_with_decision_points/hard/q2/MainTest.java
=> conditionals-programs_with_decision_points-hard-q2

src/conditionals/programs_with_decision_points/hard/q3/MainTest.java, src/conditionals/programs_with_decision_points/hard/q3/SaveTheDate.java
=> conditionals-programs_with_decision_points-hard-q3

src/pre_defined_classes/programs_with_changing_behaviour/medium/q1/MainTest.java, src/pre_defined_classes/programs_with_changing_behaviour/medium/q1/ProphetRobot.java
=> pre_defined_classes-programs_with_changing_behaviors-medium-q1

src/pre_defined_classes/programs_with_changing_behaviour/medium/q2/DnDRandom.java, src/pre_defined_classes/programs_with_changing_behaviour/medium/q2/MainTest.java
=> pre_defined_classes-programs_with_changing_behaviors-medium-q2

src/pre_defined_classes/programs_with_changing_behaviour/medium/q3/MainTest.java, src/pre_defined_classes/programs_with_changing_behaviour/medium/q3/Random8.java, src/pre_defined_classes/programs_with_changing_behaviour/medium/q3/Realist8Ball.java
=> pre_defined_classes-programs_with_changing_behaviors-medium-q3

src/pre_defined_classes/programs_with_changing_behaviour/medium/q4/MainTest.java, src/pre_defined_classes/programs_with_changing_behaviour/medium/q4/RockPaperScissors.java
=> pre_defined_classes-programs_with_changing_behaviors-medium-q4

src/pre_defined_classes/programs_with_changing_behaviour/medium/q5/MainTest.java, src/pre_defined_classes/programs_with_changing_behaviour/medium/q5/WeatherWizard.java
=> pre_defined_classes-programs_with_changing_behaviors-medium-q5

src/pre_defined_classes/programs_with_changing_behaviour/hard/q1/Cryptic.java, src/pre_defined_classes/programs_with_changing_behaviour/hard/q1/MainTest.java, src/pre_defined_classes/programs_with_changing_behaviour/hard/q2/DeCryptic.java
=> pre_defined_classes-programs_with_changing_behaviors-hard-q1

src/pre_defined_classes/programs_with_changing_behaviour/hard/q3/MainTest.java, src/pre_defined_classes/programs_with_changing_behaviour/hard/q3/PostalCode.java
=> pre_defined_classes-programs_with_changing_behaviors-hard-q3

src/pre_defined_classes/programs_with_changing_behaviour/hard/q3/MainTest.java, src/pre_defined_classes/programs_with_changing_behaviour/hard/q3/PostalCode.java
=> pre_defined_classes-programs_with_changing_behaviors-hard-q3-fixes

src/pre_defined_classes/programs_with_changing_behaviour/hard/q5/MainTest.java, src/pre_defined_classes/programs_with_changing_behaviour/hard/q5/ShuffleTime.java
=> pre_defined_classes-programs_with_changing_behaviors-hard-q5

src/conditionals/programs_with_decision_points/medium/q5Java/MainTest.java, src/conditionals/programs_with_decision_points/medium/q5Java/MammaMia.java
=>  conditionals-programs_with_decision_points-medium-q5-java

src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q5Java/MainTest.java, src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q5Java/MathSquareRoot.java
=> pre_defined_classes-simple_programs_taking_numeric_user_input-medium-q5-java

src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q5Java/LetterCalculator.java, src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q5Java/MainTest.java
=> pre_defined_classes-simple_programs_taking_numeric_user_input-hard-q5-java

src/conditionals/programs_with_decision_points/hard/q4Java/MainTest.java, src/conditionals/programs_with_decision_points/hard/q4Java/MyBestPal.java
=> conditionals-programs_with_decision_points-hard-q4-java

src/loops/simple_programs_with_repitition/medium/q2/q1/InTheBin.java, src/loops/simple_programs_with_repitition/medium/q2/q1/MainTest.java
Created folders for loops category
=> loops-file_structure

src/loops/for_loops/hard/q1/MainTest.java, src/loops/for_loops/hard/q1/RevDown.java
=> loops-for_loops-hard-q1

src/loops/for_loops/hard/q2/MainTest.java, src/loops/for_loops/hard/q2/SumAverageProgram.java
=> loops-for_loops-hard-q2

src/loops/for_loops/hard/q3/MainTest.java, src/loops/for_loops/hard/q3/Seriesly.java
=> loops-for_loops-hard-q3

src/loops/while_loops/hard/q1/MainTest.java, src/loops/while_loops/hard/q1/RevDown.java
=> loops-while_loops-hard-q1

src/loops/while_loops/hard/q2/MainTest.java, src/loops/while_loops/hard/q2/SumAverageProgram.java
=> loops-while_loops-hard-q2

src/loops/while_loops/q3/MainTest.java, src/loops/while_loops/q3/Seriesly.java
=> loops-while_loops-hard-q3

src/loops/nested_loops/hard/q1/MainTest.java, src/loops/nested_loops/hard/q1/PrimeTime.java
=> loops-nested_loops-hard-q1

src/loops/nested_loops/hard/q2/MainTest.java, src/loops/nested_loops/hard/q2/RepeatTheRepeat.java
=> loops-nested_loops-hard-q2

src/loops/nested_loops/hard/q3/MainTest.java, src/loops/nested_loops/hard/q3/TryAngle.java, src/loops/while_loops/hard/q3/MainTest.java, src/loops/while_loops/hard/q3/Seriesly.java
=> loops-nested_loops-hard-q3

src/loops/simple_programs_with_repitition/hard/q1/ArmsAreStrong.java, src/loops/simple_programs_with_repitition/hard/q1/MainTest.java
=> loops-simple_programs_with_repetition-hard-q1

src/loops/simple_programs_with_repitition/hard/q2/Jvaiava.java, src/loops/simple_programs_with_repitition/hard/q2/MainTest.java
=> loops-simple_programs_with_repetition-hard-q2

src/loops/simple_programs_with_repitition/hard/q3/MainTest.java, src/loops/simple_programs_with_repitition/hard/q3/SliceOfPi.java
=> loops-simple_programs_with_repetition-hard-q3

src/loops/programs_with_repetition/easy/q1/MainTest.java, src/loops/programs_with_repetition/easy/q1/PityPattern.java
=> loops-programs_with_repetition-easy-q1

src/loops/programs_with_repetition/easy/q3/MainTest.java, src/loops/programs_with_repetition/easy/q3/Pattern.java
=> loops-programs_with_repetition-easy-q3

src/loops/programs_with_repetition/medium/q1/DiamondCantBreak.java, src/loops/programs_with_repetition/medium/q1/MainTest.java
=> loops-programs_with_repetition-medium-q1

src/methods/using_methods/hard/q1/GotThePower.java, src/methods/using_methods/hard/q1/MainTest.java
=> methods-using_methods-hard-q1

src/methods/using_methods/hard/q2/Angles.java, src/methods/using_methods/hard/q2/MainTest.java
=> methods-using_methods-hard-q2

src/methods/defining_methods/medium/q1/MainTest.java, src/methods/defining_methods/medium/q1/RaiseToPower.java
=> methods-defining_methods-medium-q1

src/methods/defining_methods/medium/q2/AbsoluteMethod.java, src/methods/defining_methods/medium/q2/MainTest.java
=> methods-defining_methods-medium-q2

src/methods/defining_methods/hard/q1/BMIMethodTime.java, src/methods/defining_methods/hard/q1/MainTest.java
=> methods-defining_methods-hard-q1

src/methods/defining_methods/hard/q2/MainTest.java, src/methods/defining_methods/hard/q2/RadOfCircle.java
=> methods-defining_methods-hard-q2

src/methods/method_overloading/medium/q1/MainTest.java, src/methods/method_overloading/medium/q1/OverloadSum.java
=> methods-method_overloading-medium-q1

src/methods/method_overloading/medium/q2/LargerOfVars.java, src/methods/method_overloading/medium/q2/MainTest.java
=> methods-method_overloading-medium-q2

src/methods/method_overloading/hard/q1/MainTest.java, src/methods/method_overloading/hard/q1/OneToThree.java
=> methods-method_overloading-hard-q1

src/methods/method_overloading/hard/q2/MainTest.java, src/methods/method_overloading/hard/q2/Overload101.java
=> methods-method_overloading-hard-q2

src/arrays/arrays_with_methods/medium/q1/MainTest.java, src/arrays/arrays_with_methods/medium/q1/OnlyEven.java
=> arrays-arrays_with_methods-medium-q1

src/arrays/arrays_with_methods/medium/q2/HighestArray.java, src/arrays/arrays_with_methods/medium/q2/MainTest.java
=> arrays-arrays_with_methods-medium-q2

src/arrays/arrays_with_methods/medium/q3/FindIt.java, src/arrays/arrays_with_methods/medium/q3/MainTest.java
=> arrays-arrays_with_methods-medium-q3

src/arrays/arrays_with_methods/medium/q5/DivideThis.java, src/arrays/arrays_with_methods/medium/q5/MainTest.java
=> arrays-arrays_with_methods-medium-q5

src/arrays/arrays_with_methods/hard/q1/IncrementThis.java, src/arrays/arrays_with_methods/hard/q1/MainTest.java
=> arrays-arrays_with_methods-hard-q1

src/arrays/arrays_with_methods/hard/q2/Longer.java, src/arrays/arrays_with_methods/hard/q2/MainTest.java
=> arrays-arrays_with_methods-hard-q2

src/arrays/arrays_with_methods/hard/q3/MainTest.java, src/arrays/arrays_with_methods/hard/q3/SumTimes.java
=> arrays-arrays_with_methods-hard-q3

src/arrays/arrays_with_methods/hard/q4/MainTest.java, src/arrays/arrays_with_methods/hard/q4/NumbersAscend.java
=> arrays-arrays_with_methods-hard-q4

src/arrays/arrays_with_methods/hard/q5/MainTest.java, src/arrays/arrays_with_methods/hard/q5/SmallestDifference.java
=> arrays-arrays_with_methods-hard-q5

src/conditionals/programs_with_decision_points/medium/q6/Gamer.java, src/conditionals/programs_with_decision_points/medium/q6/MainTest.java
=> conditionals-programs_with_decision_points-medium-q6

src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q7/MainTest.java, src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q7/OddOrEven.java
=> pre_defined_classes-simple_programs_taking_numeric_user_input-hard-q7

src/pre_defined_classes/programs_with_changing_behaviour/medium/q6/MainTest.java, src/pre_defined_classes/programs_with_changing_behaviour/medium/q6/ShuffleMovement.java
=> pre_defined_classes-programs_with_changing_behaviors-medium-q6

src/pre_defined_classes/programs_with_changing_behaviour/medium/q7/MainTest.java, src/pre_defined_classes/programs_with_changing_behaviour/medium/q7/ShuffleChoices.java
=> pre_defined_classes-programs_with_changing_behaviors-medium-q7

src/conditionals/programs_with_decision_points/medium/q9/GenerationGap.java, src/conditionals/programs_with_decision_points/medium/q9/MainTest.java
=> conditionals-program_with_decision_points-medium-q9

src/global/BaseRandomTest.java, src/global/variables/clauses/PlaceHolder.java
+ add better logs for failing randomness tests
---
=> make placeholder nexted group non-capturing

src/global/variables/clauses/RandomChar.java
=> Add optional support for inclusive upper bounds on random char

src/global/variables/clauses/DoubleLiteral.java
=> fix double regex

src/conditionals/programs_with_decision_points/hard/q8/MainTest.java, src/conditionals/programs_with_decision_points/hard/q8/PointsScoring.java
=> conditionals-programs_with_decision_points-hard-q8

src/conditionals/programs_with_decision_points/hard/q6/MainTest.java, src/conditionals/programs_with_decision_points/hard/q6/UniversityLife.java
=> conditionals-programs_with_decision_points-hard-q6

src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q9/MainTest.java, src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q9/redditComment.java
=> pre_defined_classes-simple_programs_taking_string_user_input-medium-q9

src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q7/MainTest.java, src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q7/Syllable.java
=> pre_defined_classes-simple_programs_taking_string_user_input-hard- q7

src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q8/FlipChars.java, src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q8/MainTest.java
=>  pre_defined_classes-simple_programs_taking_string_user_input-hard-q8

src/pre_defined_classes/programs_with_changing_behaviour/medium/q9/MainTest.java, src/pre_defined_classes/programs_with_changing_behaviour/medium/q9/PlayerCharacteristics.java
=>  pre_defined_classes-programs_with_changing_behaviors-medium-q9

src/pre_defined_classes/programs_with_changing_behaviour/medium/q10/HeadsTails.java, src/pre_defined_classes/programs_with_changing_behaviour/medium/q10/MainTest.java
=> pre_defined_classes-programs_with_changing_behaviors-medium-q10

src/pre_defined_classes/programs_with_changing_behaviour/hard/q10/MainTest.java, src/pre_defined_classes/programs_with_changing_behaviour/hard/q10/ProphetBot.java
=> pre_defined_classes-programs_with_changing_behaviors-hard-q10

src/loops/simple_programs_with_repitition/hard/q8/MainTest.java, src/loops/simple_programs_with_repitition/hard/q8/VirtualSocialDistancing.java
=> loops-simple_programs_with_repetition-hard-q8

src/loops/programs_with_repetition/hard/q6/KingOfTheString.java, src/loops/programs_with_repetition/hard/q6/MainTest.java
=> loops-programs_with_repetition-hard-q6

src/loops/while_loops/hard/q8/CounterChar.java, src/loops/while_loops/hard/q8/MainTest.java
=> loops-while_loops-hard-q8

src/loops/simple_programs_with_repitition/hard/q6/MainTest.java, src/loops/simple_programs_with_repitition/hard/q6/QueryStr.java
=> loops-simple_programs_with_repetition-hard-q6

src/conditionals/programs_with_decision_points/medium/q7/JavaTopia.java, src/conditionals/programs_with_decision_points/medium/q7/MainTest.java
=> conditionals-programs_with_decision_points-medium-q7

src/conditionals/programs_with_decision_points/medium/q8/Competition.java, src/conditionals/programs_with_decision_points/medium/q8/MainTest.java
=> conditionals-programs_with_decision_points-medium-q8

src/conditionals/programs_with_decision_points/hard/q9/DrivingFines.java, src/conditionals/programs_with_decision_points/hard/q9/MainTest.java
=> conditionals-programs_with_decision_points-hard-q9

src/conditionals/programs_with_decision_points/hard/q7/MainTest.java, src/conditionals/programs_with_decision_points/hard/q7/RiskyBusiness.java
=> conditionals-programs_with_decision_points-hard-q7

src/loops/programs_with_repetition/medium/q4/MainTest.java, src/loops/programs_with_repetition/medium/q4/OurGlass.java, src/loops/programs_with_repetition/medium/q4/ThatWay.java
=> loops-programs_with_repetition-medium-q4

src/loops/for_loops/hard/q6/Factorial.java, src/loops/for_loops/hard/q6/MainTest.java
=> loops-for_loops-hard-q6

src/loops/programs_with_repetition/hard/q4/ArtificialSelection.java, src/loops/programs_with_repetition/hard/q4/MainTest.java
=> loops-programs_with_repetition-hard-q4

src/loops/programs_with_repetition/hard/q7/MainTest.java, src/loops/programs_with_repetition/hard/q7/SinOfTheTimes.java
=> loops-programs_with_repetition-hard-q7

src/loops/nested_loops/hard/q8/MainTest.java, src/loops/nested_loops/hard/q8/PrimeOrdial.java
=> loops-nested_loops-hard-q8

src/loops/simple_programs_with_repitition/easy/q2/MainTest.java, src/loops/simple_programs_with_repitition/easy/q2/VirtualBouncer.java
=> loops-simple_programs_with_repitition-easy-q2

src/loops/simple_programs_with_repitition/easy/q3/MainTest.java, src/loops/simple_programs_with_repitition/easy/q3/TimeTheTable.java
=> loops-simple_programs_with_repetition-easy-q3

src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q8/MainTest.java, src/pre_defined_classes/simple_programs_taking_string_user_input/medium/q8/UserName.java
=> pre_defined_classes-simple_programs_taking_string_user_input-medium-q8

src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q6/CanValidator.java, src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q6/MainTest.java
=> pre_defined_classes-simple_programs_taking_string_user_input-hard-q6

src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q10/MainTest.java, src/pre_defined_classes/simple_programs_taking_string_user_input/hard/q10/PasswordWeakness.java
=> pre_defined_classes-simple_programs_taking_string_user_input-hard-q10

src/loops/nested_loops/hard/q6/MainTest.java, src/loops/nested_loops/hard/q6/TryAngleButBothWaysAKAPyramid.java
=> loops-nested_loops-hard-q6

src/loops/nested_loops/hard/q7/BoxMeNow.java, src/loops/nested_loops/hard/q7/MainTest.java
=> loops-nested_loops-hard-q7

src/loops/while_loops/hard/q5/FiboWhat.java, src/loops/while_loops/hard/q5/MainTest.java
=> loops-while_loops-hard-q5

src/loops/nested_loops/hard/q4/MainTest.java, src/loops/nested_loops/hard/q4/TryAngleButTheOtherWay.java
=> loops-nested_loops-hard-q4

src/loops/programs_with_repetition/medium/q5/MainTest.java, src/loops/programs_with_repetition/medium/q5/ThatWay.java
=> loops-programs_with_repetition-medium-q5

src/loops/programs_with_repetition/medium/q4/MainTest.java, src/loops/programs_with_repetition/medium/q4/OurGlass.java, src/loops/programs_with_repetition/medium/q5/MainTest.java, src/loops/programs_with_repetition/medium/q5/ThatWay.java
Formated code and added the error message which should be printed when invalid input is encountered.
=> Fixed loops-programs_with_repetition-medium-q4/5 

src/loops/programs_with_repetition/easy/q4/ItsAlwaysPrimeTime.java, src/loops/programs_with_repetition/easy/q4/MainTest.java
=> loops-programs_with_repetition-easy-q4

src/loops/for_loops/hard/q7/MainTest.java, src/loops/for_loops/hard/q7/RevUp.java
=> loops-for_loops-hard-q7

src/loops/for_loops/hard/q8/CounterChar.java, src/loops/for_loops/hard/q8/MainTest.java
=> loops-for_loops-hard-q8

src/loops/programs_with_repetition/easy/q5/MainTest.java, src/loops/programs_with_repetition/easy/q5/MirrorSeven.java
=> loops-programs_with_repetition-easy-q5

src/loops/programs_with_repetition/hard/q5/MainTest.java, src/loops/programs_with_repetition/hard/q5/PrimeFactor.java
=> loops-programs_with_repetition-hard-q5

src/loops/simple_programs_with_repitition/hard/q7/MainTest.java, src/loops/simple_programs_with_repitition/hard/q7/PushItBack.java
=> loops-simple_programs_with_repetition-hard-q7

src/loops/simple_programs_with_repitition/hard/q5/MainTest.java, src/loops/simple_programs_with_repitition/hard/q5/NowThatsPerfect.java
=> loops-simple_programs_with_repetition-hard-q5

src/methods/modular_programs/easy/q2/FavInteger.java, src/methods/modular_programs/easy/q2/FavWholeNum.java, src/methods/modular_programs/easy/q2/MainTest.java
=> methods-modular_programs-easy-q2

src/methods/modular_programs/medium/q1/MainTest.java, src/methods/modular_programs/medium/q1/SumSum.java
=> methods-modular_programs-medium-q1

src/methods/modular_programs/medium/q2/MainTest.java, src/methods/modular_programs/medium/q2/TempConverter.java
=> methods-modular_programs-medium-q2

src/methods/modular_programs/hard/q2/AddSpaces.java, src/methods/modular_programs/hard/q2/MainTest.java
=> methods-modular_programs-hard-q2

src/methods/defining_methods/hard/q1/BMIMethodTime.java, src/methods/defining_methods/hard/q1/MainTest.java, src/methods/defining_methods/hard/q2/MainTest.java, src/methods/defining_methods/hard/q2/RadOfCircle.java, src/methods/defining_methods/medium/q1/MainTest.java, src/methods/defining_methods/medium/q1/RaiseToPower.java, src/methods/defining_methods/medium/q2/AbsoluteMethod.java, src/methods/defining_methods/medium/q2/MainTest.java, src/methods/method_overloading/hard/q1/MainTest.java, src/methods/method_overloading/hard/q1/OneToThree.java, src/methods/method_overloading/hard/q2/MainTest.java, src/methods/method_overloading/hard/q2/Overload101.java, src/methods/method_overloading/medium/q1/MainTest.java, src/methods/method_overloading/medium/q1/OverloadSum.java, src/methods/method_overloading/medium/q2/LargerOfVars.java, src/methods/method_overloading/medium/q2/MainTest.java, src/methods/modular_programs/hard/q1/MainTest.java, src/methods/modular_programs/hard/q1/RightPrime.java, src/methods/using_methods/hard/q1/GotThePower.java, src/methods/using_methods/hard/q1/MainTest.java, src/methods/using_methods/hard/q2/Angles.java, src/methods/using_methods/hard/q2/MainTest.java
These include updating older questions to use MethodUtil, increasing question variation, and updating question text.
=> Fixes and updates for methods questions

src/global/utils/ArrayUtil.java, src/test/ArrayUtilTesting.java, src/test/ArrayUtilTestingTest.java
Expanded ArrayUtil to produce random int, double, char, and string arrays, as well as functions to convert them to strings for input to `runWithInput()` and `TestOption.defaultInput`.
=> ArrayUtil Random Array Generation

src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q7/AbsoluteNumber.java, src/pre_defined_classes/simple_programs_taking_numeric_user_input/medium/q7/MainTest.java
=> pre_defined_classes-simple_programs_taking_numeric_user_input-medium-q7 

src/arrays/programs_involving_data_sequences/easy/q5/MainTest.java, src/arrays/programs_involving_data_sequences/easy/q5/RevItUp.java
=> arrays-programs_involving_data_sequences-easy-q5

src/global/tools/CustomAssertions.java
Fixed a bug where the custom assertion allowing double values was not checking types properly
=> Fixed bug with type checking

src/arrays/programs_involving_data_sequences/easy/q5/MainTest.java
For some reason, this question was causing issues and not working anymore, but is fixed now.
=> Fixed bugs with this question

src/conditionals/programs_with_decision_points/hard/q9/DrivingFines.java
=> conditionals-programs_with_decision_points-hard-q9 solution code

src/methods/defining_methods/medium/q3/LengthOfTheString.java, src/methods/defining_methods/medium/q3/MainTest.java
=> methods-defining_methods-medium-q3

src/methods/defining_methods/medium/q4/CylinderTime.java, src/methods/defining_methods/medium/q4/MainTest.java
=> methods-defining_methods-medium-q4

src/global/BaseRandomTest.java, src/global/utils/RandomUtil.java, src/global/variables/clauses/RandomDouble.java, src/test/SomewhatRandomCode.java, src/test/SomewhatRandomCodeTest.java
Fixed bug where random check was failing with random numbers and where RandomDouble was only generating one bucket
=> Randomness checking fix

src/methods/using_methods/hard/q7/MainTest.java, src/methods/using_methods/hard/q7/Using7.java, src/methods/using_methods/hard/q7/VolumeOfCube.java
=> methods-using_methods-hard-q7

src/methods/using_methods/hard/q9/MainTest.java, src/methods/using_methods/hard/q9/Tickets.java
=> methods-using_methods-hard-q9

src/methods/defining_methods/medium/q5/InverseMethod.java, src/methods/defining_methods/medium/q5/MainTest.java
=> methods-defining_methods-medium-q5

src/methods/using_methods/hard/q3/FavouriteNumber.java, src/methods/using_methods/hard/q3/MainTest.java
=> changed name for methods-using_methods-hard-q3

src/methods/defining_methods/medium/q6/MainTest.java, src/methods/defining_methods/medium/q6/VolToLength.java
=> methods-defining_methods-medium-q6

src/methods/defining_methods/medium/q8/FlourPower.java, src/methods/defining_methods/medium/q8/MainTest.java
=> methods-defining_methods-medium-q8

src/methods/defining_methods/medium/q7/MainTest.java, src/methods/defining_methods/medium/q7/PizzaPizza.java
=> methods-defining_methods-medium-q7

src/global/utils/RandomUtil.java
Added and changed some of the constants used in random checking so that all tests that should pass do so.
=> Random Testing Constant Tweaks

src/arrays/arrays_with_methods/hard/q1/MainTest.java, src/arrays/arrays_with_methods/hard/q2/MainTest.java, src/arrays/arrays_with_methods/medium/q5/MainTest.java, src/arrays/programs_involving_data_sequences/easy/q2/MainTest.java, src/arrays/programs_involving_data_sequences/hard/q1/MainTest.java, src/arrays/programs_involving_data_sequences/medium/q1/MainTest.java, src/arrays/programs_involving_data_sequences/medium/q2/MainTest.java, src/arrays/programs_involving_data_sequences/medium/q4/MainTest.java, src/arrays/programs_involving_data_sequences/medium/q5/MainTest.java, src/global/utils/ArrayUtil.java, src/test/ArrayUtilTesting.java, src/test/ArrayUtilTestingTest.java
Added methods for generating, summing, incrementing, multiplying, replicating, and other methods for manipulating arrays. This makes testing questions with arrays easier and should reduce method writing in test code.
=> Added utility methods to ArrayUtil to make testing arrays easier

src/arrays/programs_involving_data_sequences/hard/q4/MainTest.java, src/arrays/programs_involving_data_sequences/hard/q4/StringSlice.java
Moved files to correct location
=> programs_involving_data_sequences-hard-q4-file_location-fix

src/global/utils/RandomUtil.java
Decreased the number of bins for randomness testing from 50 to 20 and added a constant to store that value
=> Decreased Maximum Number of Bins for Randomness Testing

src/arrays/creatings_arrays/medium/q3/MainTest.java, src/arrays/creatings_arrays/medium/q3/RandomNum.java
=> arrays-creating_arrays-medium-q3

src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q11/Bonus.java, src/pre_defined_classes/simple_programs_taking_numeric_user_input/hard/q11/MainTest.java
=> pre_defined_classes-simple_programs_taking_numeric_user_input-hard-q11

src/arrays/arrays_with_methods/hard/q14/GeometricSequence.java, src/arrays/arrays_with_methods/hard/q14/MainTest.java
=> arrays-arrays_with_methods-hard-q14

src/loops/for_loops/hard/q9/CommonDivisors.java, src/loops/for_loops/hard/q9/MainTest.java
=> loops-for_loops-hard-q9

src/methods/modular_programs/medium/q10/GCDCalculator.java, src/methods/modular_programs/medium/q10/MainTest.java
=> methods-modular_programs-medium-q10

src/arrays/referencing_array_and_its_elements/hard/q5/MainTest.java, src/arrays/referencing_array_and_its_elements/hard/q5/StudentsNeedHelp.java
=> arrays-referencing_array_and_its_elements-hard-q5

src/arrays/multidimensional_arrays/hard/q6/MainTest.java, src/arrays/multidimensional_arrays/hard/q6/SumDiags.java
=> arrays-multidimensional_arrays-hard-q7

src/arrays/multidimensional_arrays/hard/q9/ImAWholeDimensionAhead.java, src/arrays/multidimensional_arrays/hard/q9/MainTest.java
=> arrays-multidimensional_arrays-hard-q9

src/arrays/programs_involving_multidimensional_data/easy/q4/MainTest.java, src/arrays/programs_involving_multidimensional_data/easy/q4/Rotation.java
=> arrays-programs_involving_multidimensional_data-easy-q4

src/arrays/programs_involving_multidimensional_data/easy/q6/MainTest.java, src/arrays/programs_involving_multidimensional_data/easy/q6/ValueLock.java
=> arrays-programs_involving_multidimensional_data-easy-q6

src/arrays/multidimensional_arrays/hard/q3/CountsOdd.java
=> arrays-multidimensional_arrays-hard-q3-fix

src/arrays/arrays_with_methods/medium/q7/MainTest.java
=> arrays-arrays_with_methods-medium-q7-fix

src/arrays/creating_arrays/medium/q3/MainTest.java, src/arrays/creating_arrays/medium/q3/RandomNum.java
=> arrays-creating_arrays-medium-q3-package_fix

src/arrays/programs_involving_multidimensional_data/hard/q7/MainTest.java, src/arrays/programs_involving_multidimensional_data/hard/q7/Rounding.java
=> arrays-programs_involving_multidimensional_data-hard-q7

src/arrays/programs_involving_multidimensional_data/easy/q9/MainTest.java, src/arrays/programs_involving_multidimensional_data/easy/q9/Sum.java
=> arrays-programs_involving_multidimensional_data-easy-q9

src/pre_defined_classes/programs_with_changing_behaviour/medium/q11/MainTest.java, src/pre_defined_classes/programs_with_changing_behaviour/medium/q11/WhatAScore.java
=> pre_defined_classes-programs_with_changing_behaviors-hard-q11

src/conditionals/programs_with_decision_points/hard/q12/MainTest.java, src/conditionals/programs_with_decision_points/hard/q12/SignFromTheStars.java
=> conditionals-programs_with_decision_points-hard-q12

src/arrays/multidimensional_arrays/hard/q7/MainTest.java, src/arrays/multidimensional_arrays/hard/q7/SumDiags.java
=> fixed package name

src/methods/using_methods/hard/q9/MainTest.java
=> fix-methods-using_methods-hard-q9

src/arrays/arrays_with_methods/medium/q1/MainTest.java
=> fix-arrays-arrays_with_methods-medium-q1

src/arrays/arrays_with_methods/medium/q2/MainTest.java
=> fix-arrays-arrays_with_methods-medium-q2

src/arrays/arrays_with_methods/medium/q5/MainTest.java
=> fix-arrays-arrays_with_methods-medium-q5

src/arrays/arrays_with_methods/medium/q4/MainTest.java
=> fix-arrays-arrays_with_methods-medium-q4

scripts/run_tests.py
=> attempt to fix tests

src/arrays/arrays_with_methods/hard/q1/MainTest.java
=> fix-arrays-arrays_with_methods-hard-q1

src/arrays/arrays_with_methods/hard/q2/MainTest.java
=> fix-arrays-arrays_with_methods-hard-q2

src/arrays/arrays_with_methods/hard/q3/MainTest.java
=> fix-arrays-arrays_with_methods-hard-q3

src/arrays/arrays_with_methods/hard/q4/MainTest.java
=> fix-arrays-arrays_with_methods-hard-q4

src/arrays/arrays_with_methods/hard/q5/MainTest.java
=> fix-arrays-arrays_with_methods-hard-q5

src/arrays/programs_involving_data_sequences/easy/q1/MainTest.java
=> fix-arrays-programs_involving_data_sequences-easy-q1

src/arrays/programs_involving_data_sequences/easy/q3/MainTest.java
=> fix-arrays-programs_involving_data_sequences-easy-q3

src/arrays/programs_involving_data_sequences/easy/q5/MainTest.java
=> fix-arrays-programs_involving_data_sequences-easy-q5

src/arrays/programs_involving_data_sequences/hard/q5/MainTest.java
=> fix-arrays-programs_involving_data_sequences-hard-q5

src/arrays/programs_involving_data_sequences/medium/q1/MainTest.java
=> fix-arrays-programs_involving_data_sequences-medium-q1

src/arrays/programs_involving_data_sequences/medium/q2/MainTest.java
=> fix-arrays-programs_involving_data_sequences-medium-q2

src/arrays/programs_involving_data_sequences/easy/q2/MainTest.java
=> fix-arrays-programs_involving_data_sequences-easy-q2

src/arrays/programs_involving_data_sequences/hard/q1/MainTest.java
=> fix-arrays-programs_involving_data_sequences-hard-q1

src/arrays/programs_involving_data_sequences/hard/q3/MainTest.java
=> fix-arrays-programs_involving_data_sequences-hard-q3

src/arrays/programs_involving_data_sequences/hard/q3/MainTest.java, src/arrays/programs_involving_data_sequences/hard/q4/MainTest.java
=> fix-arrays-programs_involving_data_sequences-hard-q4

src/arrays/programs_involving_data_sequences/medium/q4/MainTest.java
=> fix-arrays-programs_involving_data_sequences-medium-q4

src/arrays/programs_involving_data_sequences/medium/q5/MainTest.java
=> fix-arrays-programs_involving_data_sequences-medium-q5

src/methods/defining_methods/medium/q1/MainTest.java
=> fix-methods-defining_methods-medium-q1

src/methods/defining_methods/medium/q2/MainTest.java
=> fix-methods-defining_methods-medium-q2

src/methods/defining_methods/medium/q3/MainTest.java
=> fix-methods-defining_methods-medium-q3

src/methods/defining_methods/medium/q4/CylinderTime.java, src/methods/defining_methods/medium/q4/MainTest.java
=> fix-methods-defining_methods-medium-q4

src/methods/defining_methods/medium/q5/MainTest.java
=> fix-methods-defining_methods-medium-q5

src/methods/defining_methods/medium/q6/MainTest.java
=> fix-methods-defining_methods-medium-q6

src/methods/defining_methods/medium/q7/MainTest.java
=> fix-methods-defining_methods-medium-q7

src/methods/defining_methods/medium/q8/MainTest.java
=> fix-methods-defining_methods-medium-q8

src/methods/defining_methods/hard/q2/MainTest.java
=> fix-methods-defining_methods-hard-q2

src/methods/method_overloading/hard/q1/MainTest.java
=> fix-methods-method_overloading-hard-q1

src/methods/method_overloading/hard/q2/MainTest.java
=> fix-methods-method_overloading-hard-q2

src/methods/method_overloading/medium/q1/MainTest.java
=> fix-methods-method_overloading-medium-q1

src/methods/method_overloading/medium/q2/MainTest.java
=> fix-methods-method_overloading-medium-q2

src/methods/modular_programs/easy/q2/MainTest.java
=> fix-methods-modular_programs-easy-q2

src/methods/modular_programs/hard/q1/MainTest.java, src/methods/modular_programs/hard/q1/RightPrime.java
=> fix-methods-modular_programs-hard-q1

src/methods/modular_programs/hard/q2/MainTest.java
=> fix-methods-modular_programs-hard-q2

src/methods/modular_programs/medium/q1/MainTest.java
=> fix-methods-modular_programs-medium-q1

src/methods/using_methods/hard/q1/MainTest.java
=> fix-methods-using_methods-hard-q1

src/methods/using_methods/hard/q2/MainTest.java
=> fix-methods-using_methods-hard-q2

src/methods/using_methods/hard/q5/MainTest.java
=> fix-methods-using_methods-hard-q5

src/methods/using_methods/hard/q6/MainTest.java
=> fix-methods-using_methods-hard-q6

src/methods/using_methods/hard/q7/MainTest.java
=> fix-methods-using_methods-hard-q7

src/methods/using_methods/hard/q8/MainTest.java
=> fix-methods-using_methods-hard-q8

src/methods/modular_programs/easy/q1/MainTest.java
=> fix-methods-modular_programs-easy-q1

src/methods/using_methods/hard/q4/MainTest.java
=> fix-methods-using_methods-hard-q4

src/methods/modular_programs/medium/q2/MainTest.java
=> fix-methods-modular_programs-medium-q2

src/methods/modular_programs/hard/q10/GoatYear.java, src/methods/modular_programs/hard/q10/MainTest.java
=> methods-modular-programs-hard-q10

.github/pull_request_template.md, src/arrays/programs_involving_data_sequences/hard/q10/ArrayThereDelilah.java, src/arrays/programs_involving_data_sequences/hard/q10/MainTest.java
=> arrays-programs_involving_data_sequences-hard-q10

src/pre_defined_classes/programs_with_changing_behaviour/hard/q11/MainTest.java, src/pre_defined_classes/programs_with_changing_behaviour/hard/q11/WhatAScore.java
=> change-pre-defined_classes-programs_with_changing_behaviours-medium-q11-to_hard

src/oop/programs_with_multiple_classes/medium/q1/Chair.java, src/oop/programs_with_multiple_classes/medium/q1/MainTest.java, src/oop/programs_with_multiple_classes/medium/q1/QuestionText.md, src/oop/programs_with_multiple_classes/medium/q1/Table.java, src/oop/programs_with_multiple_classes/medium/q1/TestRoom.java
=> oop-programs_with_multiple_classes-medium-q1

src/oop/programs_with_multiple_classes/hard/q1/Circus.java, src/oop/programs_with_multiple_classes/hard/q1/MainTest.java, src/oop/programs_with_multiple_classes/hard/q1/Member.java, src/oop/programs_with_multiple_classes/hard/q1/QuestionText.md, src/oop/programs_with_multiple_classes/hard/q1/TestGroup.java
=> oop-programs_with_multiple_classes-hard-q1

src/global/ObjectTest.java, src/oop/creating_objects_from_classes/hard/q1/Dog.java, src/oop/creating_objects_from_classes/hard/q1/MainTest.java, src/oop/creating_objects_from_classes/hard/q1/Pet.java, src/oop/creating_objects_from_classes/hard/q1/QuestionText.md
=> oop-creating_objects_from_classes-hard-q1

src/global/ObjectTest.java, src/oop/user_defined_classes/medium/q1/Circle.java, src/oop/user_defined_classes/medium/q1/MainTest.java, src/oop/user_defined_classes/medium/q1/QuestionText.md
=> oop-user_defined_classes-medium-q1

src/oop/special_class_method/medium/q1/Circle.java, src/oop/special_class_method/medium/q1/MainTest.java, src/oop/special_class_method/medium/q1/QuestionText.md
=> oop-special_class_method-medium-q1

src/arrays/programs_involving_multidimensional_data/easy/q8/EvenOrOdd.java, src/arrays/programs_involving_multidimensional_data/easy/q8/MainTest.java
=> arrays-programs_involving_multidimensional_data-easy-q8

src/global/MethodTest.java, src/test/methods/MethodCode.java, src/test/methods/MethodCodeTest.java
https://github.com/canvas-gamification/canvas-gamification-junit-tests/issues/604
=> Added method in MethodTest which returns the return type of the method

src/oop/special_class_method/hard/q1/Bubble.java, src/oop/special_class_method/hard/q1/MainTest.java, src/oop/special_class_method/hard/q1/QuestionText.md, src/oop/special_class_method/hard/q1/Test.java
=> oop-special_class_method-hard-q1

src/arrays/referencing_array_and_its_elements/medium/q9/EveryEven.java, src/arrays/referencing_array_and_its_elements/medium/q9/MainTest.java
=> fix-arrays-referencing_array_and_its_elements-medium-q9

src/arrays/arrays_with_methods/hard/q8/MainTest.java, src/arrays/arrays_with_methods/hard/q8/MakeFibonacci.java
=> arrays-arrays_with_methods-hard-q8

src/oop/user_defined_classes/medium/q1/Circle.java, src/oop/user_defined_classes/medium/q1/MainTest.java, src/oop/user_defined_classes/medium/q1/QuestionText.md
Modification of the specified question.
=> oop-user_defined_classes-medium-q1-update

src/oop/user_defined_classes/hard/q1/MainTest.java, src/oop/user_defined_classes/hard/q1/QuestionText.md
Updated question to add that it is a Java question
=> oop-user_defined_classes-hard-q1-update

src/oop/object_independence/hard/q1/MainTest.java, src/oop/object_independence/hard/q1/PlatformGame.java, src/oop/object_independence/hard/q1/TestPlatformGame.java, src/oop/object_independence/hard/q1/questionText.md
=> oop-object_independence-hard-q1

src/oop/object_interactions/medium/q1/MainTest.java, src/oop/object_interactions/medium/q1/QuestionText.md, src/oop/object_interactions/medium/q1/TestTruck.java, src/oop/object_interactions/medium/q1/Truck.java
=> oop-object_interactions-medium-q1

src/global/ObjectTest.java, src/global/variables/clauses/RandomBoolean.java, src/test/random/random_boolean_testing/RandomBooleanQuestion.java, src/test/random/random_boolean_testing/RandomBooleanQuestionTest.java
Add method for randomBoolean where you can pass an ArrayList of strings to check that the values are random, and fixed an issue with calling private methods using the ObjectTest callMethod() method
=> Minor Framework Fixes and Improvements

src/global/ObjectTest.java
Due to how fields were fetched, ObjectTest did not work entirely with static fields. This has now been fixed
=> Changes to objectTest to make it work with static fields

src/oop/static_modifier/medium/q1/Circle.java, src/oop/static_modifier/medium/q1/MainTest.java, src/oop/static_modifier/medium/q1/QuesitonText.md
=> oop-static_modifier-medium-q1

src/loops/nested_loops/hard/q6/MainTest.java
=> loops-nested_loops-hard-q6-fix 

src/arrays/programs_involving_multidimensional_data/medium/q3/MainTest.java
=> arrays-programs_involving_multidimensional_data-medium-q3-fix

src/arrays/programs_involving_multidimensional_data/medium/q4/MainTest.java
=> arrays-programs_involving_multidimensional_data-medium-q4-fix

src/arrays/programs_involving_multidimensional_data/medium/q7/MainTest.java, src/arrays/programs_involving_multidimensional_data/medium/q7/MultiDivide.java
=> arrays-programs_involving_multidimensional_data-medium-q7-fix

src/global/ObjectTest.java
Added hasField method to ObjectTest to just check if a field with that name exists.
=> Added hasField function which only checks for the field name

.gitignore, src/global/tools/CustomAssertions.java, src/oop/static_modifier/hard/q1/Fence.java, src/oop/static_modifier/hard/q1/MainTest.java, src/oop/static_modifier/hard/q1/QuestionText.md, src/oop/static_modifier/hard/q1/TestPainting.java
=> oop-static_modifier-hard-q1

src/oop/programs_with_interesting_classes/easy/q3/AnnualCheckup.java, src/oop/programs_with_interesting_classes/easy/q3/MainTest.java, src/oop/programs_with_interesting_classes/easy/q3/QuestionText.md
=> Oop programs with interesting classes easy q3

src/oop/user_defined_classes/hard/q4/Laundromat.java, src/oop/user_defined_classes/hard/q4/MainTest.java, src/oop/user_defined_classes/hard/q4/QuestionText.md
=> oop-user_defined_classes-hard-q4

src/oop/user_defined_classes/hard/q3/Cupboard.java, src/oop/user_defined_classes/hard/q3/MainTest.java, src/oop/user_defined_classes/hard/q3/QuestionText.md
=> oop-user_defined_classes-hard-q3

src/oop/user_defined_classes/hard/q6/MainTest.java, src/oop/user_defined_classes/hard/q6/QuestionText.md, src/oop/user_defined_classes/hard/q6/UniversityStudent.java
=> oop-user_defined_classes-hard-q6

src/oop/user_defined_classes/hard/q7/Course.java, src/oop/user_defined_classes/hard/q7/MainTest.java, src/oop/user_defined_classes/hard/q7/QuestionText.md
=> oop-user_defined_classes-hard-q7

src/oop/object_independence/hard/q2/Fish.java, src/oop/object_independence/hard/q2/MainTest.java, src/oop/object_independence/hard/q2/QuestionText.md, src/oop/object_independence/hard/q2/TestAquarium.java
=> oop-object_independence-hard-q2

src/oop/object_independence/hard/q4/MainTest.java, src/oop/object_independence/hard/q4/Painting.java, src/oop/object_independence/hard/q4/QuestionText.md, src/oop/object_independence/hard/q4/TestMuseum.java
=> oop-object_independence-hard-q4

src/oop/object_independence/hard/q5/Glass.java, src/oop/object_independence/hard/q5/MainTest.java, src/oop/object_independence/hard/q5/QuestionText.md, src/oop/object_independence/hard/q5/TestFragile.java
=> oop-object_independence-hard-q5

src/oop/object_interactions/hard/q2/MainTest.java, src/oop/object_interactions/hard/q2/Partner.java, src/oop/object_interactions/hard/q2/QuestionText.md
=> oop-object_interactions-hard-q2

src/oop/object_interactions/hard/q5/Animal.java, src/oop/object_interactions/hard/q5/MainTest.java, src/oop/object_interactions/hard/q5/QuestionText.md, src/oop/object_interactions/hard/q5/TestExperiment.java
=> oop-object_interactions-hard-q5

src/oop/object_interactions/hard/q1/MainTest.java, src/oop/object_interactions/hard/q3/BloodDonor.java, src/oop/object_interactions/hard/q3/MainTest.java, src/oop/object_interactions/hard/q3/QuestionText.md, src/oop/object_interactions/hard/q3/TestBlood.java
=> oop-object_interactions-hard-q3

src/oop/object_interactions/hard/q4/CryptBox.java, src/oop/object_interactions/hard/q4/MainTest.java, src/oop/object_interactions/hard/q4/QuestionText.md, src/oop/object_interactions/hard/q4/TestEncryption.java
=> oop-object_interactions-hard-q4

src/oop/special_class_method/medium/q3/MainTest.java, src/oop/special_class_method/medium/q3/QuestionText.md, src/oop/special_class_method/medium/q3/Speaker.java
=> oop-special_class_method-medium-q3

src/oop/special_class_method/medium/q5/Calculator.java, src/oop/special_class_method/medium/q5/MainTest.java, src/oop/special_class_method/medium/q5/QuestionText.md
=> oop-special_class_method-medium-q5

src/oop/special_class_method/medium/q8/Luffy.java, src/oop/special_class_method/medium/q8/MainTest.java, src/oop/special_class_method/medium/q8/QuestionText.md
=> oop-special_class_method-medium-q8

src/oop/special_class_method/medium/q9/Car.java, src/oop/special_class_method/medium/q9/MainTest.java, src/oop/special_class_method/medium/q9/QuestionText.md
=> oop-special_class_method-medium-q9

src/oop/static_modifier/medium/q2/Laptop.java, src/oop/static_modifier/medium/q2/MainTest.java, src/oop/static_modifier/medium/q2/QuestionText.md, src/oop/static_modifier/medium/q2/TestObject.java
=> oop-static_modifier-medium-q2

src/oop/static_modifier/medium/q3/Horse.java, src/oop/static_modifier/medium/q3/MainTest.java, src/oop/static_modifier/medium/q3/QuestionText.md, src/oop/static_modifier/medium/q3/TestAnimal.java
=> oop-static-modifier-medium-q3

src/oop/special_class_method/hard/q10/Award.java, src/oop/special_class_method/hard/q10/MainTest.java, src/oop/special_class_method/hard/q10/QuestionText.md
=> oop-special_class_method-hard-q10

src/oop/special_class_method/hard/q2/Glasses.java, src/oop/special_class_method/hard/q2/MainTest.java, src/oop/special_class_method/hard/q2/QuestionText.md, src/oop/special_class_method/hard/q2/TestClass.java
=> oop-special_class_method-hard-q2

src/oop/special_class_method/hard/q3/Chair.java, src/oop/special_class_method/hard/q3/MainTest.java, src/oop/special_class_method/hard/q3/QuestionText.md, src/oop/special_class_method/hard/q3/TestClass.java
=> oop-special_class_method-hard-q3

src/oop/special_class_method/hard/q6/Car.java, src/oop/special_class_method/hard/q6/MainTest.java, src/oop/special_class_method/hard/q6/QuestionText.md, src/oop/special_class_method/hard/q6/TestClass.java
=> oop-special_class_method-hard-q6

src/oop/special_class_method/hard/q8/Circle.java, src/oop/special_class_method/hard/q8/MainTest.java, src/oop/special_class_method/hard/q8/QuestionText.md, src/oop/special_class_method/hard/q8/TestClass.java
=> oop-special_class_method-hard-q8

src/oop/special_class_method/hard/q7/MainTest.java, src/oop/special_class_method/hard/q7/PiggyBank.java, src/oop/special_class_method/hard/q7/QuestionText.md, src/oop/special_class_method/hard/q7/TestClass.java
=> oop-special_class_method-hard-q7

src/oop/special_class_method/hard/q9/Earth.java, src/oop/special_class_method/hard/q9/MainTest.java, src/oop/special_class_method/hard/q9/QuestionText.md
=> oop-special_class_method-hard-q9

src/oop/object_independence/medium/q4/MainTest.java, src/oop/object_independence/medium/q4/PortableMusicPlayer.java, src/oop/object_independence/medium/q4/QuestionText.md
=> oop-object_independence-medium-q4

src/oop/object_independence/medium/q5/MainTest.java, src/oop/object_independence/medium/q5/QuestionText.md, src/oop/object_independence/medium/q5/Team.java
=> oop-object_independence-medium-q5

src/oop/creating_objects_from_classes/hard/q6/MainTest.java, src/oop/creating_objects_from_classes/hard/q6/Martini.java, src/oop/creating_objects_from_classes/hard/q6/MartiniSample.java, src/oop/creating_objects_from_classes/hard/q6/OrderDrink.java, src/oop/creating_objects_from_classes/hard/q6/QuestionText.md
=> oop-creating_objects_from_classes-hard-q6

src/global/ObjectTest.java, src/oop/static_modifier/medium/q4/ChemistryLab.java, src/oop/static_modifier/medium/q4/MainTest.java, src/oop/static_modifier/medium/q4/QuestionText.md
=> oop-static_modifier-medium-q4

src/oop/special_class_method/medium/q10/MainTest.java, src/oop/special_class_method/medium/q10/QuestionText.md, src/oop/special_class_method/medium/q10/Shoe.java
=> oop-special_class_method-medium-q10

src/oop/programs_with_interesting_classes/hard/q1/BuildVocab.java, src/oop/programs_with_interesting_classes/hard/q1/MainTest.java, src/oop/programs_with_interesting_classes/hard/q1/QuestionText.md, src/oop/programs_with_interesting_classes/hard/q1/WordSearch.java
=> oop-programs_with_interesting_classes-hard-q1

src/arrays/programs_involving_multidimensional_data/hard/q4/MainTest.java, src/arrays/programs_involving_multidimensional_data/hard/q4/TicTac.java
=> arrays-programs_involving_multidimensional_data-hard-q4

src/oop/object_interactions/medium/q5/MainTest.java, src/oop/object_interactions/medium/q5/Person.java, src/oop/object_interactions/medium/q5/QuestionText.md, src/oop/object_interactions/medium/q5/TestTransplant.java
=> oop-object_interactions-medium-q5

src/oop/object_interactions/medium/q6/Airplane.java, src/oop/object_interactions/medium/q6/MainTest.java, src/oop/object_interactions/medium/q6/QuestionText.md, src/oop/object_interactions/medium/q6/TestBooking.java
=> oop-object_interactions-medium-q6

src/oop/static_modifier/medium/q5/Hat.java, src/oop/static_modifier/medium/q5/MainTest.java, src/oop/static_modifier/medium/q5/QuestionText.md, src/oop/static_modifier/medium/q5/Test.java
=> oop-static_modifier-medium-q5

src/oop/special_class_method/medium/q11/MainTest.java, src/oop/special_class_method/medium/q11/Oven.java, src/oop/special_class_method/medium/q11/QuestionText.md
=> oop-special_class_method-medium-q11

src/oop/special_class_method/medium/q12/MainTest.java, src/oop/special_class_method/medium/q12/QuestionText.md, src/oop/special_class_method/medium/q12/Shirt.java
=> oop-special_class_method-medium-q12

src/oop/special_class_method/medium/q13/Detergent.java, src/oop/special_class_method/medium/q13/MainTest.java, src/oop/special_class_method/medium/q13/QuestionText.md
=> oop-special_class_method-medium-q13

src/oop/special_class_method/medium/q14/MainTest.java, src/oop/special_class_method/medium/q14/QuestionText.md, src/oop/special_class_method/medium/q14/Water.java
=> oop-special_class_method-medium-q14

src/global/ObjectTest.java, src/oop/special_class_method/hard/q12/Laptop.java, src/oop/special_class_method/hard/q12/MainTest.java, src/oop/special_class_method/hard/q12/QuestionText.md
=> oop-special_class_method-hard-q12

src/oop/special_class_method/hard/q11/Alien.java, src/oop/special_class_method/hard/q11/MainTest.java, src/oop/special_class_method/hard/q11/QuestionText.md, src/oop/special_class_method/hard/q12/Laptop.java, src/oop/special_class_method/hard/q12/MainTest.java, src/oop/special_class_method/hard/q12/QuestionText.md, src/oop/special_class_method/medium/q13/Detergent.java, src/oop/special_class_method/medium/q13/MainTest.java, src/oop/special_class_method/medium/q13/QuestionText.md, src/oop/special_class_method/medium/q14/MainTest.java, src/oop/special_class_method/medium/q14/QuestionText.md, src/oop/special_class_method/medium/q14/Water.java
=> Swap in missing to string methods for special class method

src/global/ObjectTest.java, src/oop/special_class_method/hard/q13/Cup.java, src/oop/special_class_method/hard/q13/MainTest.java, src/oop/special_class_method/hard/q13/QuestionText.md
=> oop-special_class_method-hard-q13

src/oop/special_class_method/hard/q14/Bottle.java, src/oop/special_class_method/hard/q14/MainTest.java, src/oop/special_class_method/hard/q14/QuestionText.md
=> oop-special_class_method-hard-q14

src/oop/programs_with_interesting_classes/easy/q4/MainTest.java, src/oop/programs_with_interesting_classes/easy/q4/QuestionText.md, src/oop/programs_with_interesting_classes/easy/q4/Tree.java
=> oop-programs_with_interesting_classes-easy-q4

src/oop/programs_with_interesting_classes/easy/q5/Discord.java, src/oop/programs_with_interesting_classes/easy/q5/MainTest.java, src/oop/programs_with_interesting_classes/easy/q5/QuestionText.md, src/oop/programs_with_interesting_classes/easy/q5/TestSocialMedia.java
=> oop-programs_with_interesting_classes-easy-q5

src/oop/programs_with_interesting_classes/easy/q7/MainTest.java, src/oop/programs_with_interesting_classes/easy/q7/Playlist.java, src/oop/programs_with_interesting_classes/easy/q7/QuestionText.md, src/oop/programs_with_interesting_classes/easy/q7/Song.java, src/oop/programs_with_interesting_classes/easy/q7/Test.java
=> oop-programs_with_interesting_classes-easy-q7

src/oop/programs_with_interesting_classes/easy/q8/Activity.java, src/oop/programs_with_interesting_classes/easy/q8/MainTest.java, src/oop/programs_with_interesting_classes/easy/q8/QuestionText.md, src/oop/programs_with_interesting_classes/easy/q8/TestWaterUsage.java
=> oop-programs_with_interesting_classes-easy-q8

src/oop/static_modifier/hard/q7/MainTest.java, src/oop/static_modifier/hard/q7/QuestionText.md, src/oop/static_modifier/hard/q7/RoadTrip.java, src/oop/static_modifier/hard/q7/Taxes.java
=> oop-static_modifier-hard-q7

src/oop/static_modifier/medium/q6/MainTest.java, src/oop/static_modifier/medium/q6/QuestionText.md, src/oop/static_modifier/medium/q6/TextProcessing.java
=> added static variable and changed question and test accordingly

src/oop/creating_objects_from_classes/hard/q4/MainTest.java
=> fix_creating_objects_from_classes-hard-q4-failure

src/arrays/multidimensional_arrays/hard/q2/MainTest.java, src/arrays/multidimensional_arrays/hard/q2/SimpleDisplay.java, src/arrays/multidimensional_arrays/hard/q5/MainTest.java, src/arrays/multidimensional_arrays/hard/q5/SumAverageProgram.java, src/arrays/multidimensional_arrays/hard/q6/MainTest.java, src/arrays/multidimensional_arrays/hard/q6/OneAndOneMakeTwoDArrays.java
=> Update multidimensional arrays to be fully compliant with category progression

src/oop/programs_with_interesting_classes/medium/q1/MainTest.java
=> fix-oop-programs_with_interesting_classes-medium-q1

src/oop/programs_with_interesting_classes/medium/q3/MainTest.java, src/oop/programs_with_interesting_classes/medium/q3/Pokemon.java, src/oop/programs_with_interesting_classes/medium/q3/QuestionText.md, src/oop/programs_with_interesting_classes/medium/q3/TestPokemon.java
=> oop-programs_with_interesting_classes-medium-q3

src/oop/programs_with_interesting_classes/medium/q4/MainTest.java, src/oop/programs_with_interesting_classes/medium/q4/Mario.java, src/oop/programs_with_interesting_classes/medium/q4/QuestionText.md, src/oop/programs_with_interesting_classes/medium/q4/TestPlatformer.java
=> oop-programs_with_interesting_classes-medium-q4

src/oop/programs_with_interesting_classes/medium/q5/Card.java, src/oop/programs_with_interesting_classes/medium/q5/Hand.java, src/oop/programs_with_interesting_classes/medium/q5/MainTest.java, src/oop/programs_with_interesting_classes/medium/q5/PlayGame.java, src/oop/programs_with_interesting_classes/medium/q5/QuestionText.md
=> oop-programs_with_interesting_classes-medium-q5

src/oop/programs_with_interesting_classes/medium/q6/Horse.java, src/oop/programs_with_interesting_classes/medium/q6/MainTest.java, src/oop/programs_with_interesting_classes/medium/q6/QuestionText.md, src/oop/programs_with_interesting_classes/medium/q6/RaceTrack.java
=> oop-programs_with_interesting_classes-medium-q6

src/oop/programs_with_interesting_classes/medium/q7/HotSoup.java, src/oop/programs_with_interesting_classes/medium/q7/LunchRush.java, src/oop/programs_with_interesting_classes/medium/q7/MainTest.java, src/oop/programs_with_interesting_classes/medium/q7/QuestionText.md, src/oop/programs_with_interesting_classes/medium/q7/VendingMachine.java
=> oop-programs_with_interesting_classes-medium-q7

src/oop/programs_with_interesting_classes/medium/q8/Food.java, src/oop/programs_with_interesting_classes/medium/q8/Fridge.java, src/oop/programs_with_interesting_classes/medium/q8/MainTest.java, src/oop/programs_with_interesting_classes/medium/q8/QuestionText.md, src/oop/programs_with_interesting_classes/medium/q8/TestSmartFoodManagement.java
=> oop-programs_with_interesting_classes-medium-q8

src/oop/programs_with_interesting_classes/medium/q9/MainTest.java, src/oop/programs_with_interesting_classes/medium/q9/Movie.java, src/oop/programs_with_interesting_classes/medium/q9/QuestionText.md, src/oop/programs_with_interesting_classes/medium/q9/Review.java, src/oop/programs_with_interesting_classes/medium/q9/TestExpertReviews.java
=> oop-programs_with_interesting_classes-medium-q9

src/oop/programs_with_interesting_classes/medium/q10/Cashier.java, src/oop/programs_with_interesting_classes/medium/q10/MainTest.java, src/oop/programs_with_interesting_classes/medium/q10/QuestionText.md, src/oop/programs_with_interesting_classes/medium/q10/TestShopping.java
=> oop-programs_with_interesting_classes-medium-q10

src/oop/programs_with_interesting_classes/medium/q8/Fridge.java, src/oop/programs_with_interesting_classes/medium/q8/MainTest.java
=> fix-oop-programs_with_interesting_classes-medium-q8

src/oop/programs_with_interesting_classes/hard/q1/QuestionText.md, src/oop/programs_with_interesting_classes/hard/q2/CandyCrush.java, src/oop/programs_with_interesting_classes/hard/q2/LeaderBoard.java, src/oop/programs_with_interesting_classes/hard/q2/MainTest.java, src/oop/programs_with_interesting_classes/hard/q2/Player.java, src/oop/programs_with_interesting_classes/hard/q2/QuestionText.md
=> oop-programs_with_interesting_classes-hard-q2

src/oop/programs_with_interesting_classes/hard/q3/MainTest.java, src/oop/programs_with_interesting_classes/hard/q3/Person.java, src/oop/programs_with_interesting_classes/hard/q3/QuestionText.md, src/oop/programs_with_interesting_classes/hard/q3/Team.java, src/oop/programs_with_interesting_classes/hard/q3/TeamFormation.java
=> oop-programs_with_interesting_classes-hard-q3

src/oop/programs_with_interesting_classes/hard/q4/Ad.java, src/oop/programs_with_interesting_classes/hard/q4/CraigsList.java, src/oop/programs_with_interesting_classes/hard/q4/MainTest.java, src/oop/programs_with_interesting_classes/hard/q4/QuestionText.md
=> oop-programs_with_interesting_classes-hard-q4

src/oop/programs_with_interesting_classes/hard/q5/ExploreJobs.java, src/oop/programs_with_interesting_classes/hard/q5/JobAd.java, src/oop/programs_with_interesting_classes/hard/q5/MainTest.java, src/oop/programs_with_interesting_classes/hard/q5/QuestionText.md
=> oop-programs_with_interesting_classes-hard-q5

src/oop/programs_with_interesting_classes/hard/q4/QuestionText.md, src/oop/programs_with_interesting_classes/hard/q8/Course.java, src/oop/programs_with_interesting_classes/hard/q8/MainTest.java, src/oop/programs_with_interesting_classes/hard/q8/QuestionText.md, src/oop/programs_with_interesting_classes/hard/q8/TestSemester.java
=> oop-programs_with_interesting_classes-hard-q8

src/oop/programs_with_interesting_classes/hard/q9/Book.java, src/oop/programs_with_interesting_classes/hard/q9/Borrower.java, src/oop/programs_with_interesting_classes/hard/q9/Library.java, src/oop/programs_with_interesting_classes/hard/q9/MainTest.java, src/oop/programs_with_interesting_classes/hard/q9/QuestionText.md
=> oop-programs_with_interesting_classes-hard-q9

src/oop/programs_with_interesting_classes/hard/q10/Employee.java, src/oop/programs_with_interesting_classes/hard/q10/MainTest.java, src/oop/programs_with_interesting_classes/hard/q10/QuestionText.md, src/oop/programs_with_interesting_classes/hard/q10/StoreHours.java, src/oop/programs_with_interesting_classes/hard/q10/WorkSchedule.java
=> oop-programs_with_interesting_classes-hard-q10

src/conditionals/programs_with_decision_points/medium/q11/MainTest.java, src/conditionals/programs_with_decision_points/medium/q11/WeatherConditions.java
=> Conditionals programs with decision points medium q11

.vscode/settings.json, src/conditionals/programs_with_decision_points/medium/q10/CoffeeOrder.java, src/conditionals/programs_with_decision_points/medium/q10/MainTest.java
=> Conditionals programs with decision points medium q10

src/conditionals/simple_programs_with_decision_points/medium/q9/DoubleIt.java, src/conditionals/simple_programs_with_decision_points/medium/q9/MainTest.java
=> Conditionals simple programs medium q9

src/conditionals/simple_programs_with_decision_points/hard/q9/GradeToLetter.java, src/conditionals/simple_programs_with_decision_points/hard/q9/MainTest.java
=> Conditionals simple programs hard q9

src/conditionals/programs_with_decision_points/hard/q14/MainTest.java, src/conditionals/programs_with_decision_points/hard/q14/checkWord.java
=> Programs with simple decision points q14

src/conditionals/simple_programs_with_decision_points/hard/q8/MainTest.java, src/conditionals/simple_programs_with_decision_points/hard/q8/sumToFifty.java
=> Conditionals simple programs q8
